const playersData = [
  {
    id: "donk",
    rank: 1,
    name: "donk",
    role: "Rifler / Entry Fragger",
    teamName: "Team Spirit",
    teamUrl: "teams/team-spirit.html",
    avatar: "images/donk.jpg",
    age: 19,
    rating: "1.34",
    stats: { firepower: 98, entrying: 96, trading: 88, opening: 95, clutching: 78, sniping: 20, utility: 72 }
  },
  {
    id: "monesy",
    rank: 2,
    name: "m0NESY",
    role: "AWPer",
    teamName: "G2 Esports",
    teamUrl: "teams/g2.html",
    avatar: "images/monesy.jpg",
    age: 21,
    rating: "1.31",
    stats: { firepower: 96, entrying: 82, trading: 86, opening: 88, clutching: 95, sniping: 98, utility: 70 }
  },
  {
    id: "zywoo",
    rank: 3,
    name: "ZywOo",
    role: "AWPer",
    teamName: "Team Vitality",
    teamUrl: "teams/vitality.html",
    avatar: "images/zywoo.jpg",
    age: 25,
    rating: "1.29",
    stats: { firepower: 95, entrying: 80, trading: 90, opening: 85, clutching: 96, sniping: 92, utility: 84 }
  },
  {
    id: "sh1ro",
    rank: 4,
    name: "sh1ro",
    role: "AWPer",
    teamName: "Team Spirit",
    teamUrl: "teams/team-spirit.html",
    avatar: "images/sh1ro.jpg",
    age: 25,
    rating: "1.22",
    stats: { firepower: 88, entrying: 68, trading: 91, opening: 75, clutching: 97, sniping: 94, utility: 78 }
  },
  {
    id: "b1bit",
    rank: 5,
    name: "b1t",
    role: "Rifler",
    teamName: "Natus Vincere",
    teamUrl: "teams/navi.html",
    avatar: "images/b1t.jpg",
    age: 23,
    rating: "1.18",
    stats: { firepower: 90, entrying: 82, trading: 85, opening: 80, clutching: 75, sniping: 15, utility: 74 }
  },
  {
    id: "ropz",
    rank: 6,
    name: "ropz",
    role: "Rifler / Lurker",
    teamName: "FaZe Clan",
    teamUrl: "teams/faze.html",
    avatar: "images/ropz.jpg",
    age: 26,
    rating: "1.16",
    stats: { firepower: 86, entrying: 65, trading: 89, opening: 72, clutching: 92, sniping: 25, utility: 86 }
  },
  {
    id: "frozen",
    rank: 7,
    name: "frozen",
    role: "Rifler",
    teamName: "FaZe Clan",
    teamUrl: "teams/faze.html",
    avatar: "images/frozen.jpg",
    age: 24,
    rating: "1.16",
    stats: { firepower: 87, entrying: 75, trading: 88, opening: 78, clutching: 82, sniping: 30, utility: 80 }
  },
  {
    id: "niko",
    rank: 8,
    name: "NiKo",
    role: "Rifler / Entry Fragger",
    teamName: "G2 Esports",
    teamUrl: "teams/g2.html",
    avatar: "images/niko.jpg",
    age: 29,
    rating: "1.15",
    stats: { firepower: 94, entrying: 90, trading: 84, opening: 92, clutching: 76, sniping: 35, utility: 76 }
  },
  {
    id: "jL",
    rank: 9,
    name: "jL",
    role: "Rifler / Support",
    teamName: "Natus Vincere",
    teamUrl: "teams/navi.html",
    avatar: "images/jl.jpg",
    age: 26,
    rating: "1.15",
    stats: { firepower: 88, entrying: 80, trading: 82, opening: 81, clutching: 88, sniping: 20, utility: 82 }
  },
  {
    id: "w3nderful",
    rank: 10,
    name: "w3nderful",
    role: "AWPer",
    teamName: "Natus Vincere",
    teamUrl: "teams/navi.html",
    avatar: "images/w3nderful.jpg",
    age: 21,
    rating: "1.14",
    stats: { firepower: 84, entrying: 70, trading: 85, opening: 76, clutching: 89, sniping: 90, utility: 72 }
  },
  {
    id: "flamez",
    rank: 11,
    name: "flameZ",
    role: "Entry Fragger",
    teamName: "Team Vitality",
    teamUrl: "teams/vitality.html",
    avatar: "images/flamez.jpg",
    age: 23,
    rating: "1.13",
    stats: { firepower: 89, entrying: 92, trading: 79, opening: 88, clutching: 68, sniping: 15, utility: 70 }
  },
  {
    id: "xertion",
    rank: 12,
    name: "xertioN",
    role: "Entry Fragger",
    teamName: "MOUZ",
    teamUrl: "teams/mouz.html",
    avatar: "images/xertion.jpg",
    age: 22,
    rating: "1.13",
    stats: { firepower: 88, entrying: 91, trading: 80, opening: 86, clutching: 70, sniping: 10, utility: 74 }
  },
  {
    id: "torzsi",
    rank: 13,
    name: "torzsi",
    role: "AWPer",
    teamName: "MOUZ",
    teamUrl: "teams/mouz.html",
    avatar: "images/torzsi.jpg",
    age: 24,
    rating: "1.12",
    stats: { firepower: 83, entrying: 68, trading: 82, opening: 74, clutching: 85, sniping: 89, utility: 76 }
  },
  {
    id: "jimpphat",
    rank: 14,
    name: "Jimpphat",
    role: "Rifler / Anchor",
    teamName: "MOUZ",
    teamUrl: "teams/mouz.html",
    avatar: "images/jimpphat.jpg",
    age: 19,
    rating: "1.12",
    stats: { firepower: 85, entrying: 64, trading: 88, opening: 70, clutching: 90, sniping: 15, utility: 84 }
  },
  {
    id: "spinx",
    rank: 15,
    name: "Spinx",
    role: "Rifler / Lurker",
    teamName: "Team Vitality",
    teamUrl: "teams/vitality.html",
    avatar: "images/spinx.jpg",
    age: 25,
    rating: "1.11",
    stats: { firepower: 85, entrying: 68, trading: 87, opening: 72, clutching: 88, sniping: 20, utility: 80 }
  },
  {
    id: "broky",
    rank: 16,
    name: "broky",
    role: "AWPer",
    teamName: "FaZe Clan",
    teamUrl: "teams/faze.html",
    avatar: "images/broky.jpg",
    age: 25,
    rating: "1.11",
    stats: { firepower: 82, entrying: 65, trading: 84, opening: 72, clutching: 96, sniping: 88, utility: 78 }
  },
  {
    id: "elige",
    rank: 17,
    name: "EliGE",
    role: "Rifler / Entry Fragger",
    teamName: "Complexity",
    teamUrl: "teams/complexity.html",
    avatar: "images/elige.jpg",
    age: 29,
    rating: "1.11",
    stats: { firepower: 91, entrying: 89, trading: 80, opening: 88, clutching: 72, sniping: 20, utility: 75 }
  },
  {
    id: "brollan",
    rank: 18,
    name: "Brollan",
    role: "Rifler / Space Creator",
    teamName: "MOUZ",
    teamUrl: "teams/mouz.html",
    avatar: "images/brollan.jpg",
    age: 24,
    rating: "1.10",
    stats: { firepower: 84, entrying: 86, trading: 81, opening: 83, clutching: 72, sniping: 15, utility: 73 }
  },
  {
    id: "iM",
    rank: 19,
    name: "iM",
    role: "Rifler / Entry Fragger",
    teamName: "Natus Vincere",
    teamUrl: "teams/navi.html",
    avatar: "images/im.jpg",
    age: 27,
    rating: "1.10",
    stats: { firepower: 85, entrying: 87, trading: 78, opening: 84, clutching: 74, sniping: 10, utility: 75 }
  },
  {
    id: "magisk",
    rank: 20,
    name: "Magisk",
    role: "Rifler / Anchor",
    teamName: "Team Falcons",
    teamUrl: "teams/falcons.html",
    avatar: "images/magisk.jpg",
    age: 28,
    rating: "1.09",
    stats: { firepower: 82, entrying: 66, trading: 85, opening: 71, clutching: 91, sniping: 20, utility: 88 }
  },
  {
    id: "rain",
    rank: 21,
    name: "rain",
    role: "Entry Fragger",
    teamName: "FaZe Clan",
    teamUrl: "teams/faze.html",
    avatar: "images/rain.jpg",
    age: 31,
    rating: "1.08",
    stats: { firepower: 84, entrying: 88, trading: 81, opening: 85, clutching: 78, sniping: 15, utility: 76 }
  },
  {
    id: "device",
    rank: 22,
    name: "device",
    role: "AWPer / IGL",
    teamName: "Astralis",
    teamUrl: "teams/astralis.html",
    avatar: "images/device.jpg",
    age: 30,
    rating: "1.08",
    stats: { firepower: 82, entrying: 68, trading: 84, opening: 75, clutching: 86, sniping: 88, utility: 82 }
  },
  {
    id: "stavn",
    rank: 23,
    name: "stavn",
    role: "Rifler",
    teamName: "Astralis",
    teamUrl: "teams/astralis.html",
    avatar: "images/stavn.jpg",
    age: 24,
    rating: "1.08",
    stats: { firepower: 83, entrying: 74, trading: 83, opening: 77, clutching: 78, sniping: 35, utility: 80 }
  },
  {
    id: "jabbi",
    rank: 24,
    name: "jabbi",
    role: "Rifler / Lurker",
    teamName: "Astralis",
    teamUrl: "teams/astralis.html",
    avatar: "images/jabbi.jpg",
    age: 23,
    rating: "1.07",
    stats: { firepower: 82, entrying: 70, trading: 84, opening: 73, clutching: 85, sniping: 20, utility: 79 }
  },
  {
    id: "chopper",
    rank: 25,
    name: "chopper",
    role: "IGL",
    teamName: "Team Spirit",
    teamUrl: "teams/team-spirit.html",
    avatar: "images/chopper.jpg",
    age: 29,
    rating: "1.06",
    stats: { firepower: 76, entrying: 78, trading: 75, opening: 74, clutching: 70, sniping: 10, utility: 90 }
  },
  {
    id: "siuhy",
    rank: 26,
    name: "siuhy",
    role: "IGL",
    teamName: "MOUZ",
    teamUrl: "teams/mouz.html",
    avatar: "images/siuhy.jpg",
    age: 23,
    rating: "1.05",
    stats: { firepower: 78, entrying: 76, trading: 78, opening: 75, clutching: 75, sniping: 15, utility: 92 }
  },
  {
    id: "aleksib",
    rank: 27,
    name: "Aleksib",
    role: "IGL",
    teamName: "Natus Vincere",
    teamUrl: "teams/navi.html",
    avatar: "images/aleksib.jpg",
    age: 29,
    rating: "1.04",
    stats: { firepower: 74, entrying: 68, trading: 76, opening: 70, clutching: 78, sniping: 15, utility: 96 }
  },
  {
    id: "karrigan",
    rank: 28,
    name: "karrigan",
    role: "IGL",
    teamName: "FaZe Clan",
    teamUrl: "teams/faze.html",
    avatar: "images/karrigan.jpg",
    age: 36,
    rating: "1.02",
    stats: { firepower: 72, entrying: 80, trading: 72, opening: 78, clutching: 70, sniping: 20, utility: 94 }
  },
  {
    id: "apex",
    rank: 29,
    name: "apEX",
    role: "IGL",
    teamName: "Team Vitality",
    teamUrl: "teams/vitality.html",
    avatar: "images/apex.jpg",
    age: 33,
    rating: "1.02",
    stats: { firepower: 75, entrying: 82, trading: 75, opening: 80, clutching: 72, sniping: 10, utility: 95 }
  },
  {
    id: "mezii",
    rank: 30,
    name: "mezii",
    role: "Rifler / Support",
    teamName: "Team Vitality",
    teamUrl: "teams/vitality.html",
    avatar: "images/mezii.jpg",
    age: 27,
    rating: "1.02",
    stats: { firepower: 78, entrying: 65, trading: 82, opening: 68, clutching: 84, sniping: 20, utility: 90 }
  },
  {
    id: "hunter",
    rank: 31,
    name: "huNter-",
    role: "Rifler / Lurker",
    teamName: "G2 Esports",
    teamUrl: "teams/g2.html",
    avatar: "images/hunter.jpg",
    age: 30,
    rating: "1.01",
    stats: { firepower: 80, entrying: 70, trading: 82, opening: 72, clutching: 80, sniping: 15, utility: 80 }
  },
  {
    id: "snax",
    rank: 32,
    name: "Snax",
    role: "IGL",
    teamName: "G2 Esports",
    teamUrl: "teams/g2.html",
    avatar: "images/snax.jpg",
    age: 33,
    rating: "0.99",
    stats: { firepower: 73, entrying: 62, trading: 76, opening: 68, clutching: 85, sniping: 25, utility: 88 }
  },
  {
    id: "snappi",
    rank: 33,
    name: "Snappi",
    role: "IGL",
    teamName: "Team Falcons",
    teamUrl: "teams/falcons.html",
    avatar: "images/snappi.jpg",
    age: 36,
    rating: "0.98",
    stats: { firepower: 70, entrying: 72, trading: 71, opening: 72, clutching: 68, sniping: 10, utility: 91 }
  },
  {
    id: "s1mple",
    rank: 34,
    name: "s1mple",
    role: "AWPer",
    teamName: "Team Falcons",
    teamUrl: "teams/falcons.html",
    avatar: "images/s1mple.jpg",
    age: 28,
    rating: "1.18",
    stats: { firepower: 93, entrying: 82, trading: 85, opening: 85, clutching: 92, sniping: 95, utility: 75 }
  },
  {
    id: "hallzerk",
    rank: 35,
    name: "hallzerk",
    role: "AWPer",
    teamName: "Complexity",
    teamUrl: "teams/complexity.html",
    avatar: "images/hallzerk.jpg",
    age: 26,
    rating: "1.07",
    stats: { firepower: 81, entrying: 66, trading: 80, opening: 73, clutching: 82, sniping: 88, utility: 70 }
  }
];